apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9hcHA6YWRtaW5AY2x1c3RlcjAubjdtc2p3dC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZQ==
  PORT: NTAwMA==
