apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: prod
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    role: backend
