apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dilipdevsecops-in
  namespace: stage
spec:
  secretName: deltacapita-com-tls
  duration: 2160h 
  renewBefore: 720h  
  subject:
    organizations:
      - delta capita
  commonName: deltacapita.com
  dnsNames:
    - deltacapita.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
