apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-secrets-manager
  namespace: stage
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-secrets-binding
  namespace: stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-secrets-manager
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
