apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    role: frontend
  ports:
    - port: 8080  # External port
      targetPort: 8080  # Internal port
      protocol: TCP
  type: LoadBalancer
