apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  selector:
    role: frontend
  ports:
    - port: 3000  # External port
      targetPort: 3000  # Internal port
      protocol: TCP
  type: LoadBalancer
