apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  selector:
    role: frontend
  ports:
    - port: 80  # External port
      targetPort: 3000  # Internal port
      protocol: TCP
  type: LoadBalancer
