apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  namespace: prod
  labels:
    app: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: IMAGE_TAG_PLACEHOLDER
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_URL
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: PORT
