apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer  # Changed to LoadBalancer to support a load balancer
  selector:
   role: backend
