apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  namespace: prod
  labels:
    app: backend
spec:
  replicas: 3  # Increase replicas for better availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  # To ensure smooth rolling updates
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: public.ecr.aws/t3p0g8h2/backend:latest
        imagePullPolicy: IfNotPresent  # Only pull image if not already present
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /ok
            port: 5000
          initialDelaySeconds: 10  # Increase initial delay to allow startup time
          periodSeconds: 15  # Adjust probe interval based on application behavior
        readinessProbe:
          httpGet:
             path: /ok
             port: 5000
          initialDelaySeconds: 15  # Increase initial delay to allow startup time
          periodSeconds: 20  # Adjust probe interval based on application behavior
          successThreshold: 1
        resources:  # Add resource requests and limits for better resource management
          requests:
            cpu: 100m  # Request 100 milli CPU
            memory: 128Mi  # Request 128 MiB memory
          limits:
            cpu: 200m  # Limit to 200 milli CPU
            memory: 256Mi  # Limit to 256 MiB memory
