apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: prod
spec:
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
    nodePort: 30000  # Specify your desired nodePort here
  type: NodePort
  selector:
    role: frontend
